[package]
name = "lpc55_sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_struct = "0.10.0"
packed_struct_codegen = "0.10.0"
clap = { version = "3.0.14", features = ["derive"] }
anyhow = "1.0.32"
byteorder = "1.3.4"
ecdsa = { version = "0.16.0", default-features = false, features = ["pkcs8", "der"] }
p256 = { version = "0.13.0", features = ["pkcs8"] }
elliptic-curve = { version = "0.13.1", default-features = false }
hex = "0.4.3"
crc-any = "2.3.5"
x509-parser = { version = "0.12.0", features = ["verify"] }
sha2 = "0.9.8"
rsa = { version = "0.8.1", features = ["sha2"] }
lpc55_areas = { path = "../lpc55_areas", features = [] }
serde = { version = "1", features = ["derive"] }
toml = "0.5.6"
parse_int = "0.6.0"
colored = "2.0"

[features]
default = ["binaries"]
binaries = []

[[bin]]
name = "lpc55_sign"
test = false
bench = false
required-features = ["binaries"]
